### ISSUE TITLE
Apple Silicon architecture support for development

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srganalytics-apple#49]
### Issue type

Feature request

### Description of the problem

> As a developer, I want to build my project with SRG library dependencies in the simulator on my Apple Silicon Mac
> so that I can develop apps on it.

<img width="200" alt="Screenshot 2021-01-13 at 10 42 49" src="https://user-images.githubusercontent.com/380522/104471812-94492900-55bb-11eb-80e6-03acc4e888ef.png">

> Thank you @TorstenKaufmann for the shared screen.

The current Letterbox version has 3 binary dependencies: TCCore, TCSDK and Comscore.
Those binary libraries have to be updated to have ARM simulator architecture included.

### Environment information

* Library version: 6.1.2
* iOS / tvOS version: Any -> Use Mac OS Big Sure with arm M1 processor
* Device: Any simulator

### Reproducibility

Always reproducible

### Steps to reproduce

1. Open Demo workspace on an Apple Silicon Mac.
1. Build and run the demo target on an iOS simulator.

**Comment by defagos** [comment]
Binaries for Catalyst / M1 **need** to be [built with `macosx` as platform](https://github.com/SRGSSR/srganalytics-apple/issues/49#issuecomment-765500705), otherwise Xcode will find duplicate binaries.

I just tested the TCCore SDK beta tag you created on M1, but as expected integration with SPM fails with _While building for Mac Catalyst, no library for this platform was found_.

**Comment by defagos** [comment]
M1 support was introduced for comScore in version 6.8.0. I could successfully run the analytics demo on M1 (iOS and tvOS simulators).

**Comment by TorstenKaufmann** [comment]
A big Thank You from a lonely M1 user.  🙋‍♂️

**Comment by defagos** [comment]
Delivered in version 7.0.4.
