### ISSUE TITLE
Archiving issue

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srganalytics-apple#53]
Projects using SRG Analytics cannot be properly archived.

### Issue type

Incorrect behavior

### Environment information

* Library version: 7.0.2
* iOS / tvOS version: Any
* Device: -

### Reproducibility

Always reproducible

### Steps to reproduce

1. Add SRG Analytics to an app with SPM.
1. Attempt to archive the app.

**Comment by defagos** [comment]
The workaround can be quite surprising, as we test `canImport(Combine)` instead of the expected `canImport(SwiftUI)`. But testing for SwiftUI import works, so we reused the [same trick](https://github.com/SRGSSR/srgdataprovider-apple/issues/30) as for SRG Data Provider. This is safe as Combine and SwiftUI were introduced at the same time.

SRG Analytics will soon be iOS 12+ anyway and we'll likely be able to remove this workaround.
